### ISSUE TITLE
_ExpoSecureStore.default.getValueWithKeyAsync is not a function

### ISSUE THREAD

**Issue by lucasmsoares96** [get-convex/convex-auth#114]
I am following the authentication documentation ([link](https://labs.convex.dev/auth/setup)) for Expo web and google oauth. However, when I click on the SignIn button with the google account, the following error message appears in the browser console:

```
SecureStore.js:84  Uncaught (in promise) TypeError: _ExpoSecureStore.default.getValueWithKeyAsync is not a function
    at Object.getItemAsync [as getItem] (SecureStore.js:84:34)
    at client.js:254:53
    at client.js:112:33
    at handleSignIn (SignIn.tsx:11:36)
    at onClick (PressResponder.js:314:13)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
    at executeDispatch (react-dom.development.js:9041:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:7)
    at processDispatchQueue (react-dom.development.js:9086:5)
    at dispatchEventsForPlugins (react-dom.development.js:9097:3)
    at react-dom.development.js:9288:12
    at batchedUpdates$1 (react-dom.development.js:26140:12)
    at batchedUpdates (react-dom.development.js:3991:12)
    at dispatchEventForPluginEventSystem (react-dom.development.js:9287:3)
    at dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay (react-dom.development.js:6465:5)
    at dispatchEvent (react-dom.development.js:6457:5)
    at dispatchDiscreteEvent (react-dom.development.js:6430:5)
```

The same problem does not happen on Android.

**Comment by dowski** [comment]
Hi, do you see that error on the browser console on a mobile device or are you attempting to use it for a regular web app?

I wonder if this SO answer might be relevant: https://stackoverflow.com/a/78728352

**Comment by lucasmsoares96** [comment]
The problem happens when I try to open an expo web application in the macos browser.

**Comment by Zwyx** [comment]
I got the same issue and suggest a fix in PR #149.
