### ISSUE TITLE
Uncaught Error: Invalid redirectTo URI http://localhost:8081

### ISSUE THREAD

**Issue by lucasmsoares96** [get-convex/convex-auth#115]
When running the code from the [expo-convex-auth repository](https://github.com/get-convex/expo-convex-auth) or following the [convex auth documentation](https://labs.convex.dev/auth) with Expo to set up OAuth with Google Sign In, I get the following error when clicking the Sign In button:

```
  "code": "[Request ID: 923d45806d831583] Server Error: Uncaught Error: Invalid redirectTo URI http://localhost:8081",
  "trace": "Uncaught Error: Invalid redirectTo URI http://localhost:8081\n    at redirect (../../convex/auth.ts:40:6)\n    at redirectAbsoluteUrl (../../node_modules/@convex-dev/auth/dist/server/implementation/redirects.js:8:4)\n    at <anonymous> (../../node_modules/@convex-dev/auth/dist/server/implementation/index.js:183:36)\n    at invokeFunction (../../node_modules/convex/src/server/impl/registration_impl.ts:79:2)\n    at invokeHttpAction (../../node_modules/convex/src/server/impl/registration_impl.ts:422:0)\n    at q.invokeHttpAction [as invokeHttpAction] (../../node_modules/convex/src/server/impl/registration_impl.ts:448:9)\n    at <anonymous> (../../node_modules/convex/src/server/router.ts:322:16)\n"
}
```

The issue occurs on both Expo Web and Android (not tested on iOS).

**Comment by franckdsf** [comment]
I'm having the same issue with NextJS
```
{"code":"[Request ID: XXXXXXXX] Server Error: Uncaught Error: Invalid `redirectTo` http://localhost:3000 for configured SITE_URL: \thttp://localhost:3000","trace":"Uncaught Error: Invalid `redirectTo` http://localhost:3000 for configured SITE_URL: \thttp://localhost:3000\n"}
```
